# Site Settings
title: Dan Nguyen
description: "Personal Portfolio and Projects"
url: "https://dannguyen111.github.io" 
baseurl: ""
linkedin_url: "https://www.linkedin.com/in/dannguyen111/"

# Build Settings
markdown: kramdown

# Collections Configuration
collections:
  projects:
    output: true
    permalink: /projects/:slug/
